### ISSUE TITLE
Modifying scopes and removing final in dependencies

### ISSUE THREAD

**Issue by flug** [stevebauman/unfinalize#4]
I came across your project which modifies the scopes (`private`, `public`, etc.) and removes the `final` keyword from all dependency classes. Here are some points to consider:

1. **Licenses**: Depending on the license (MIT, GPL, etc.), modifying the code can have legal implications.
2. **Author's Intentions**: Design choices like `final` or `private` are often intentional and have specific reasons.
3. **Liability**: Modifications might introduce bugs or security vulnerabilities.
4. **Ethics**: Even if it's legal, is it ethically right to alter someone else's work in this manner?

It might be wise to reassess this approach or consult a software law expert.

**Comment by stevebauman** [comment]
Hey @flug,

Make sure you also post this on [composer-patches](https://github.com/cweagans/composer-patches). There are many more modification capabilities to vendor code there.

> Licenses: Depending on the license (MIT, GPL, etc.), modifying the code can have legal implications.

Not my problem.

> Author's Intentions: Design choices like final or private are often intentional and have specific reasons.

That's ok.

> Liability: Modifications might introduce bugs or security vulnerabilities.

Not my problem.

> Ethics: Even if it's legal, is it ethically right to alter someone else's work in this manner?

Yes.

> It might be wise to reassess this approach or consult a software law expert.

I think Unfinalize works great. No need to reassess or consult anybody 👍

**Comment by Whax** [comment]
Distressing response, don't change, you're awesome...

**Comment by shalvah** [comment]
Hilarious to see people losing their shit over this.
